# 빌드 스테이지
FROM python:3.12-slim as builder

WORKDIR /app
COPY ./requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# 런타임 스테이지
FROM python:3.12-slim

WORKDIR /app
COPY --from=builder /root/.local /root/.local
COPY . ./app

# 5️⃣ 환경 변수 설정 (PYTHONPATH 추가)
ENV PYTHONPATH="/app"

ENV PATH=/root/.local/bin:$PATH
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0"]